force-app/main/default/objects/Plant_Asset__c/Plant_Asset__c.object-meta.xml
<CustomObject>
    <description>All the assets of customers</description>
    <label>Plant Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Assets (Account)</relationshipLabel>
    <relationshipName>Plant_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Assigned_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact for Onboarding</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plant Assets</relationshipLabel>
    <relationshipName>Plant_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Implementation_Status__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Status__c</fullName>
    <label>Implementation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Lifecycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Submission</fullName>
                <default>true</default>
                <label>Pending Customer Submission</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Pending Full Documentation Submission</fullName>
                <isActive>false</isActive>
                <label>Pending Full Documentation Submission</label>
            </value>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
                <isActive>false</isActive>
                <label>Submitted – Pending Customer Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plant_Asset__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Parent Asset</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>Plant Assets (Child)</relationshipLabel>
    <relationshipName>Plant_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <inlineHelpText>Please enter the minimum required name of the asset. This field will then be concatenated with Customer plant asset ID to arrive at the asset name.</inlineHelpText>
    <label>Plant Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Data Connection</fullName>
            </value>
            <value>
                <fullName>Data Validation</fullName>
            </value>
            <value>
                <fullName>Customer Validation</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI__c/RFI__c.object-meta.xml
<CustomObject>
    <label>RFI</label>
    <nameField>
        <label>RFI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/Assigned_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact for Onboarding</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/Implementation_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Implementation Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot create an RFI while plant asset is in this Project Lifecycle Status. Change status to appropriate PLS to create RFI</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RFI_Categories__c/RFI_Categories__c.object-meta.xml
<CustomObject>
    <label>RFI Category</label>
    <nameField>
        <label>RFI Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI_Categories__c/fields/Category_Classification__c.field-meta.xml
<CustomField>
    <fullName>Category_Classification__c</fullName>
    <description>Category Classification (General,Solar,Wind,Other )</description>
    <label>Category Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Assigned_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact for Onboarding</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Category_Classification__c.field-meta.xml
<CustomField>
    <fullName>Category_Classification__c</fullName>
    <label>Category Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Implementation_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Implementation Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Incorrect_Category__c.field-meta.xml
<CustomField>
    <fullName>Incorrect_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incorrect Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipName>RFI_Incorrect_Information_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Missing_Incomplete_Category__c.field-meta.xml
<CustomField>
    <fullName>Missing_Incomplete_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Missing/Incomplete Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipName>RFI_Missing_Incorrect_Information_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Description__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Description__c</fullName>
    <label>Onsite Remediation Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Required__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Required__c</fullName>
    <label>Onsite Remediation Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot edit RFI until Plant Asset&apos;s Project Lifecycle Status is changed</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Detail_Description__c.field-meta.xml
<CustomField>
    <fullName>RFI_Detail_Description__c</fullName>
    <label>RFI Item Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Number__c.field-meta.xml
<CustomField>
    <fullName>RFI_Number__c</fullName>
    <label>RFI Number</label>
    <referenceTo>RFI__c</referenceTo>
    <relationshipName>RFI_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssetNameTest.cls
@isTest(SeeAllData='true')
public class AssetNameTest {
 /*   
 @isTest
    static void testAssetname()
    {
        Plant_Asset__c p = new Plant_Asset__c();
        p.Customer_Plant_Asset_ID__c='Test';
        p.Plant_Name__c = 'Test1';
        insert p;
    }
*/
    
    @isTest
    static void testRFI()
    {
         Account newAcc = new Account();
        newAcc.Name = 'Test ACC';
        insert newAcc;
         Contact c = new Contact();
        c.LastName = 'Test Name';
        c.AccountId = newAcc.Id;
        c.Email='Kranthi.d@congruentindai.com';
        insert c;
      
        system.debug('contact--->'+ c);
        newAcc.Primary_Contact__c = c.Id;
        update newAcc;
     
     /*User u = new User(
     ProfileId = [SELECT Id FROM Profile WHERE Name = 'PF Community'].Id,
     LastName = 'last',
     Email = 'puser000@cittest.com',
     Username = 'puser000@cittest.com' + System.currentTimeMillis(),
     CompanyName = 'TEST',
     Title = 'title',
     Alias = 'alias',
     TimeZoneSidKey = 'America/Los_Angeles',
     EmailEncodingKey = 'UTF-8',
     LanguageLocaleKey = 'en_US',
     LocaleSidKey = 'en_US',
     ContactId = c.Id
    );
      
      insert u;      */  
        Plant_Asset__c palntAsset = new Plant_Asset__c();
        palntAsset.Name = 'Plant Asset st';
        palntAsset.RecordTypeId = [SELECT id from RecordType where Name ='Parent Asset'].Id;
        palntAsset.Project_Lifecycle_Status__c = 'Pending';
        palntAsset.Plant_Name__c = 'test';
        palntAsset.Implementation_Status__c = 'Pending Customer Submission';
        insert palntAsset;
        
        Plant_Asset__c palntAss = new Plant_Asset__c();
        palntAss.Name = 'Customer Asset Test';
        palntAss.RecordTypeId = [SELECT id from RecordType where Name ='Customer Asset'].Id;
        palntAss.Parent__c = palntAsset.Id;
        palntAss.Plant_Name__c = 'test123';
        palntAss.Customer_Plant_Asset_ID__c = '123';
        palntAss.Account__c = newAcc.Id;
        palntAss.Assigned_Customer_Contact__c = c.Id;
        insert palntAss;
        
        palntAss.Project_Lifecycle_Status__c = 'Data Validation';
        palntAss.Implementation_Status__c = 'In Progress';
        Update palntAss;
        
        RFI__c newrfi = new RFI__c();
        newrfi.Plant_Asset__c = palntAss.Id;
        insert newrfi;
        
        
    } 
    @isTest
    static void testRFI1()
    {
         Account newAcc = new Account();
        newAcc.Name = 'Test ACC';
        insert newAcc;
         Contact c = new Contact();
        c.LastName = 'Test Name';
        c.AccountId = newAcc.Id;
        c.Email='Kranthi.d@congruentindai.com';
        insert c;
      
        system.debug('contact--->'+ c);
        
        newAcc.Primary_Contact__c = c.Id;
        update newAcc;
    /* User u = new User(
     ProfileId = [SELECT Id FROM Profile WHERE Name = 'PF Community'].Id,
     LastName = 'last',
     Email = 'puser000@cittest.com',
     Username = 'puser000@cittest.com' + System.currentTimeMillis(),
     CompanyName = 'TEST',
     Title = 'title',
     Alias = 'alias',
     TimeZoneSidKey = 'America/Los_Angeles',
     EmailEncodingKey = 'UTF-8',
     LanguageLocaleKey = 'en_US',
     LocaleSidKey = 'en_US',
     ContactId = c.Id
    );
      
      insert u;  */  
        Plant_Asset__c palntAsset = new Plant_Asset__c();
        palntAsset.Name = 'Plant Asset Test';
        palntAsset.RecordTypeId = [SELECT id from RecordType where Name ='Parent Asset'].Id;
        palntAsset.Project_Lifecycle_Status__c = 'Pending';
        palntAsset.Plant_Name__c = 'test';
        palntAsset.Implementation_Status__c = 'Pending Customer Submission';
        insert palntAsset;
        
        Plant_Asset__c palntAss = new Plant_Asset__c();
        palntAss.Name = 'Customer Asset Test';
        palntAss.RecordTypeId = [SELECT id from RecordType where Name ='Customer Asset'].Id;
        palntAss.Parent__c = palntAsset.Id;
        palntAss.Plant_Name__c = 'test123';
        palntAss.Customer_Plant_Asset_ID__c = '123';
        palntAss.Account__c = newAcc.Id;
        palntAss.Assigned_Customer_Contact__c = c.Id;
        insert palntAss;
        
        palntAss.Project_Lifecycle_Status__c = 'Data Validation';
        palntAss.Implementation_Status__c = 'In Progress';
        Update palntAss;
        
        RFI__c newrfi = new RFI__c();
        newrfi.Plant_Asset__c = palntAss.Id;
        insert newrfi;
        
         RFI_Categories__c rfiCat = new RFI_Categories__c();
        rfiCat.Name = 'COD';
        rfiCat.RecordTypeId = [SELECT id from RecordType where Name ='Incorrect Information'].Id;
        rfiCat.Description__c='Description__c';
        rfiCat.Category_Classification__c='General';
         insert rfiCat;
        RFI_Categories__c rfiCat1 = new RFI_Categories__c();
        rfiCat1.Name = 'AC/DC Capacity';
        rfiCat.RecordTypeId = [SELECT id from RecordType where Name ='Missing/Incomplete Information'].Id;
        rfiCat1.Description__c='Description1';
        rfiCat1.Category_Classification__c='Solar';
        insert rfiCat1;
        
        RFI_Detail__c rfDetail = new RFI_Detail__c();
        rfDetail.Name = 'test rfi detail 1';
        rfDetail.RFI_Number__c = newrfi.id;
        //rfDetail.RFI_Detail_Description__c = 'test';
        rfDetail.Onsite_Remediation_Required__c = 'Yes';
        rfDetail.Onsite_Remediation_Description__c ='Test';
        rfDetail.Missing_Incomplete_Category__c=rfiCat1.Id;
        //rfDetail.Implementation_Blocked__c = false;
        //rfDetail.Due_Date__c = Date.today().addDays(-8);
        insert rfDetail;
        
        RFI_Detail__c rfDetail1 = new RFI_Detail__c();
        rfDetail1.Name = 'test1234';
        rfDetail1.RFI_Number__c = newrfi.id;
        rfDetail1.Onsite_Remediation_Required__c = 'Yes';
        rfDetail1.Onsite_Remediation_Description__c ='Test';
        rfDetail1.Customer_Comments__c ='Test area';
        rfDetail.Incorrect_Category__c = rfiCat.Id;
        // rfDetail1.Due_Date__c = Date.today().addDays(-8);
        insert rfDetail1;
        
        palntAss.Plant_Name__c='hello test';
        palntAss.Customer_Plant_Asset_ID__c='test hi';
        update palntAss;
        
    }
        
    
}