force-app/main/default/objects/Plant_Asset__c/Plant_Asset__c.object-meta.xml
<CustomObject>
    <description>All the assets of customers</description>
    <label>Plant Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Asset__c/fields/Implementation_Status__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Status__c</fullName>
    <label>Implementation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Lifecycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Submission</fullName>
                <default>true</default>
                <label>Pending Customer Submission</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Pending Full Documentation Submission</fullName>
                <isActive>false</isActive>
                <label>Pending Full Documentation Submission</label>
            </value>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
                <isActive>false</isActive>
                <label>Submitted – Pending Customer Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI__c/RFI__c.object-meta.xml
<CustomObject>
    <label>RFI</label>
    <nameField>
        <label>RFI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI__c/fields/Implementation_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Implementation Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot create an RFI while plant asset is in this Project Lifecycle Status. Change status to appropriate PLS to create RFI</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/RFI_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Status__c</fullName>
    <label>RFI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
                <isActive>false</isActive>
                <label>Cannot Complete</label>
            </value>
            <value>
                <fullName>Completed – Pending PF Review</fullName>
                <isActive>false</isActive>
                <label>Completed – Pending PF Review</label>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
                <isActive>false</isActive>
                <label>Needs Detail</label>
            </value>
            <value>
                <fullName>New – Pending Customer Review (New)</fullName>
                <isActive>false</isActive>
                <label>New – Pending Customer Review (New)</label>
            </value>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
                <isActive>false</isActive>
                <label>Submitted – Pending Customer Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI_Detail__c/fields/Implementation_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Implementation Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot edit RFI until Plant Asset&apos;s Project Lifecycle Status is changed</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Item_Status__c</fullName>
    <label>RFI Item Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
            </value>
            <value>
                <fullName>Completed – Pending PF Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Completed - Pending PF Review</fullName>
                <isActive>false</isActive>
                <label>Completed - Pending PF Review</label>
            </value>
            <value>
                <fullName>Submitted - pending customer review</fullName>
                <isActive>false</isActive>
                <label>Submitted - pending customer review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Number__c.field-meta.xml
<CustomField>
    <fullName>RFI_Number__c</fullName>
    <label>RFI Number</label>
    <referenceTo>RFI__c</referenceTo>
    <relationshipName>RFI_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/updateRFIstatus.cls
public class updateRFIstatus {
    public static void getrfidetails(List<RFI_Detail__c> rfiDetailsLst){
        Set<Id> rfiId= new Set<Id>();
        System.debug('rfiDetailsLst' +rfiDetailsLst.size());
        for(RFI_Detail__c a : rfiDetailsLst){
            rfiId.add(a.RFI_Number__c);
        }
        list<RFI_Detail__c> rfiDetail = [SELECT Id, RFI_Number__c, RFI_Item_Status__c, Implementation_Blocked__c FROM RFI_Detail__c WHERE RFI_Number__c =:rfiId];
        Map<Id,List<RFI_Detail__c>> mapRfiwiseRfidetails = new Map<Id,List<RFI_Detail__c>>();
        for(RFI_Detail__c b:rfiDetail){
            if(mapRfiwiseRfidetails.containsKey(b.RFI_Number__c))
            {
                List<RFI_Detail__c> lstRFId = mapRfiwiseRfidetails.get(b.RFI_Number__c);
                lstRFId.add(b);
            }
            
            else
            {
                List<RFI_Detail__c> lstRFId = new List<RFI_Detail__c>();
                lstRFId.add(b);
                mapRfiwiseRfidetails.put(b.RFI_Number__c,lstRFId);
            }
        }
        system.debug(mapRfiwiseRfidetails);
        for(ID idVar :mapRfiwiseRfidetails.keySet()){
            list<RFI_Detail__c> closedlst = new list<RFI_Detail__c>();
            list<RFI_Detail__c> inprogresslst = new list<RFI_Detail__c>();
            list<RFI_Detail__c> submittedlst = new list<RFI_Detail__c>();
            list<RFI_Detail__c> iblsttrue = new list<RFI_Detail__c>();
            list<RFI_Detail__c> iblstfalse = new list<RFI_Detail__c>();
            for(RFI_Detail__c rfiVar : mapRfiwiseRfidetails.get(idVar)){
                if(rfiVar.RFI_Item_Status__c == 'Closed' || rfiVar.RFI_Item_Status__c == 'Canceled' || 
                   rfiVar.RFI_Item_Status__c == 'Cannot Complete'){
                    closedlst.add(rfiVar);
                   }
                if(rfiVar.RFI_Item_Status__c == 'In Progress' || rfiVar.RFI_Item_Status__c == 'Needs Detail' ||
                   rfiVar.RFI_Item_Status__c == 'Completed – Pending PF Review'){
                       inprogresslst.add(rfiVar);
                   }
                if(rfiVar.RFI_Item_Status__c == 'Submitted – Pending Customer Review'){
                       submittedlst.add(rfiVar);
                   }
                if(rfiVar.Implementation_Blocked__c == true && (rfiVar.RFI_Item_Status__c == 'In Progress' || rfiVar.RFI_Item_Status__c == 'Needs Detail' || 
                   rfiVar.RFI_Item_Status__c == 'Completed – Pending PF Review' || rfiVar.RFI_Item_Status__c == 'Completed – Pending PF Review')){
                       iblsttrue.add(rfiVar);
                   }
                if(rfiVar.Implementation_Blocked__c == false || (rfiVar.Implementation_Blocked__c == true && (rfiVar.RFI_Item_Status__c == 'Closed' || rfiVar.RFI_Item_Status__c == 'Canceled' || 
                   rfiVar.RFI_Item_Status__c == 'Cannot Complete'))){
                       iblstfalse.add(rfiVar);
                   }
            }
            //system.debug(closedlst);
            //system.debug(inprogresslst);
            //system.debug(submittedlst);
            system.debug(iblsttrue);
            RFI__c  statusUpdate = [SELECT id,Plant_Asset__c, RFI_Status__c FROM RFI__c WHERE id =:idVar LIMIT 1];
            //RFI__c  IbUpdate = [SELECT id, RFI_Status__c FROM RFI__c WHERE id =:idVar LIMIT 1];
            
            if(inprogresslst.size() == mapRfiwiseRfidetails.get(idVar).size()){
                //RFI__c  inprogress = [SELECT id, RFI_Status__c FROM RFI__c WHERE id =:idVar LIMIT 1];
                //system.debug(inprogress);
                statusUpdate.RFI_Status__c = 'In Progress';
                update statusUpdate;
            }
            if(submittedlst.size() == mapRfiwiseRfidetails.get(idVar).size()){
                //RFI__c  statusUpdate = [SELECT id, RFI_Status__c FROM RFI__c WHERE id =:idVar LIMIT 1];
                //system.debug(submitted);
                statusUpdate.RFI_Status__c = 'Submitted';
                update statusUpdate;
            }
            if(iblsttrue != null){
                statusUpdate.Implementation_Blocked__c = true;
                update statusUpdate;
                 Plant_Asset__c plantAsset = [select id,Implementation_Status__c from Plant_Asset__c where id=:statusUpdate.Plant_Asset__c limit 1];
                 plantAsset.Implementation_Status__c='Blocked';
                 update plantAsset;
            }
            if(iblstfalse.size() == mapRfiwiseRfidetails.get(idVar).size()){
                statusUpdate.Implementation_Blocked__c = false;
                Plant_Asset__c plantAsset = [select id,Implementation_Status__c from Plant_Asset__c where id=:statusUpdate.Plant_Asset__c limit 1];
                update statusUpdate; 
                plantAsset.Implementation_Status__c='In Progress';
                 update plantAsset;
                
            }
            if( closedlst.size() == mapRfiwiseRfidetails.get(idVar).size() ){
                //RFI__c  closed = [SELECT id, RFI_Status__c FROM RFI__c WHERE id =:idVar LIMIT 1];
                //system.debug(closed);
                statusUpdate.RFI_Status__c = 'Closed';
                update statusUpdate;
            }
            if( submittedlst.size() != mapRfiwiseRfidetails.get(idVar).size()){
                if( closedlst.size() != mapRfiwiseRfidetails.get(idVar).size()){
                	//RFI__c  closed = [SELECT id, RFI_Status__c FROM RFI__c WHERE id =:idVar LIMIT 1];
                	//system.debug(closed);
                	statusUpdate.RFI_Status__c = 'In Progress';
                	update statusUpdate;
            	}
            }
        }
    }
    
}