force-app/main/default/objects/Plant_Asset__c/Plant_Asset__c.object-meta.xml
<CustomObject>
    <description>All the assets of customers</description>
    <label>Plant Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Asset__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Full_Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Plant_Name__c</fullName>
    <inlineHelpText>Please enter the full name of the plant here. This field will be used by customers for identifying their assets</inlineHelpText>
    <label>Full Plant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMEC</fullName>
            </value>
            <value>
                <fullName>Bay4</fullName>
            </value>
            <value>
                <fullName>Biosar</fullName>
            </value>
            <value>
                <fullName>Blattner Energy</fullName>
            </value>
            <value>
                <fullName>Borrego Solar</fullName>
            </value>
            <value>
                <fullName>Buenavista Renewables</fullName>
            </value>
            <value>
                <fullName>CalCom</fullName>
            </value>
            <value>
                <fullName>Carolina Solar Services, LLC</fullName>
            </value>
            <value>
                <fullName>CCR</fullName>
            </value>
            <value>
                <fullName>CED OpCo</fullName>
            </value>
            <value>
                <fullName>Coldwell Solar</fullName>
            </value>
            <value>
                <fullName>Coles Electric</fullName>
            </value>
            <value>
                <fullName>Cupertino Electric</fullName>
            </value>
            <value>
                <fullName>Depcom</fullName>
            </value>
            <value>
                <fullName>DynaSolar</fullName>
            </value>
            <value>
                <fullName>E.ON</fullName>
            </value>
            <value>
                <fullName>Ecoplexus, Inc</fullName>
            </value>
            <value>
                <fullName>EDF</fullName>
            </value>
            <value>
                <fullName>Elecnor</fullName>
            </value>
            <value>
                <fullName>Enerparc</fullName>
            </value>
            <value>
                <fullName>ESA Renewables, LLC</fullName>
            </value>
            <value>
                <fullName>EV-Assurance Power Systems</fullName>
            </value>
            <value>
                <fullName>EV-Besco</fullName>
            </value>
            <value>
                <fullName>EV-Electrical Power and Controls</fullName>
            </value>
            <value>
                <fullName>EV-FSGI</fullName>
            </value>
            <value>
                <fullName>EV-Gervais Electric</fullName>
            </value>
            <value>
                <fullName>EV-JNS Power and Control Systems</fullName>
            </value>
            <value>
                <fullName>EV-K&amp;R Construction Specialties, Inc</fullName>
            </value>
            <value>
                <fullName>EV-Kenmor Electric</fullName>
            </value>
            <value>
                <fullName>EV-Maximum Solar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Plant_Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Plant_Business_Segment__c</fullName>
    <inlineHelpText>Select Business Unit for the Plant from the picklist</inlineHelpText>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BESS</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>EV</fullName>
            </value>
            <value>
                <fullName>Resi</fullName>
            </value>
            <value>
                <fullName>ROC-Not Monitored</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>WWS Construction</fullName>
            </value>
            <value>
                <fullName>WWS Solar</fullName>
            </value>
            <value>
                <fullName>WWS Wind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <inlineHelpText>Please enter the minimum required name of the asset. This field will then be concatenated with Customer plant asset ID to arrive at the asset name.</inlineHelpText>
    <label>Plant Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Service_Region__c.field-meta.xml
<CustomField>
    <fullName>Service_Region__c</fullName>
    <description>The Service Region provides an ability to organize Asset Tags in a distributed workforce environment. Service Region is copied to the Work Order.</description>
    <inlineHelpText>The Service Region provides an ability to organize Asset Tags in a distributed workforce environment. Service Region is copied to the Work Order.</inlineHelpText>
    <label>Service Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2085-NSW</fullName>
            </value>
            <value>
                <fullName>2085-QLD</fullName>
            </value>
            <value>
                <fullName>2085-SA</fullName>
            </value>
            <value>
                <fullName>2085-VIC</fullName>
            </value>
            <value>
                <fullName>2085-WA</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA - Central</fullName>
            </value>
            <value>
                <fullName>CA - North</fullName>
            </value>
            <value>
                <fullName>CA - South</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DG - AZ</fullName>
            </value>
            <value>
                <fullName>DG - CA - Central</fullName>
            </value>
            <value>
                <fullName>DG - CA - North</fullName>
            </value>
            <value>
                <fullName>DG - CA - South</fullName>
            </value>
            <value>
                <fullName>DG - CO</fullName>
            </value>
            <value>
                <fullName>DG - CT</fullName>
            </value>
            <value>
                <fullName>DG - DC</fullName>
            </value>
            <value>
                <fullName>DG - DE</fullName>
            </value>
            <value>
                <fullName>DG - FL</fullName>
            </value>
            <value>
                <fullName>DG - GA</fullName>
            </value>
            <value>
                <fullName>DG - HI</fullName>
            </value>
            <value>
                <fullName>DG - IL</fullName>
            </value>
            <value>
                <fullName>DG - MA</fullName>
            </value>
            <value>
                <fullName>DG - MD</fullName>
            </value>
            <value>
                <fullName>DG - MN</fullName>
            </value>
            <value>
                <fullName>DG - MO</fullName>
            </value>
            <value>
                <fullName>DG - MT</fullName>
            </value>
            <value>
                <fullName>DG - NC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/classes/ParentAccountControllerTest.cls
@isTest
private class ParentAccountControllerTest{

    
    static testMethod void myUnitTest1() {
        
        Account parentAcct = new Account ();
        parentAcct.Name = 'Parent Account 1';
        parentAcct.Account_Email__c = 'parentuser@gmail.com';
        parentAcct.Customer_ID__c = '1005';
        insert parentAcct;
        
        Account a1 = new Account();
        a1.Name = 'Project Account Test';
        a1.Account_Email__c = 'anyuser@gmail.com';
        a1.Site = 'www.google.com';
        insert a1;
        
        Contact c1 = new Contact();
        c1.FirstName = 'Test first name';
        c1.LastName = 'Test last name';
        c1.Email = 'contactemail@gmail.com';
        c1.Phone = '5546747737';
        c1.AccountId = a1.Id;
        insert c1;
        
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Plant_Asset__c; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = AccountRecordTypeInfo.get('Location').getRecordTypeId();
        
        Plant_Asset__c assetTag = new Plant_Asset__c();
        assetTag.Name = '1021.0001 - Plant';
        assetTag.Plant_Business_Segment__c = 'EV';
        assetTag.Operator__c = 'CalCom';
        assetTag.Service_Region__c = 'DG - CO';
        assetTag.RecordTypeId = rtId;
         assetTag.Plant_Name__c ='test';
        assetTag.Customer_Plant_Asset_ID__c='678.908';
        assetTag.Full_plant_name__c='test 123345';
        insert assetTag;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(parentAcct);
        ParentAccountController c = new ParentAccountController(sc);
        PageReference pageRef = Page.ParentAccountPage;
        pageRef.getParameters().put('id', String.valueOf(parentAcct.Id));
        Test.setCurrentPage(pageRef);
        c.account = new Account();
        c.account.Name = 'Project Account Test';
        c.account.ParentId = parentAcct.id;
        c.account.Account_Email__c = 'anyuser@gmail.com';
        c.account.Site = 'www.google.com';
        c.accountNext();
        
        c.contact.FirstName = 'Test first name';
        c.contact.LastName = 'Test last name';
        c.contact.Email = 'contactemail@gmail.com';
        c.contact.Phone = '5546747737';
        c.contactNext();
        
        c.contactPrevious();
        //c.assetTagPrevious();
        c.cancel();
       // c.populateCustomerId();
        c.save();
    }
    
    static testMethod void myUnitTest2() {
        
        Account parentAcct = new Account ();
        parentAcct.Name = 'Parent Account 1';
        parentAcct.Account_Email__c = 'parentuser@gmail.com';
        parentAcct.Customer_ID__c = '1005';
        insert parentAcct;
        
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Plant_Asset__c; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = AccountRecordTypeInfo.get('Location').getRecordTypeId();
        
        Plant_Asset__c assetTag = new Plant_Asset__c();
        assetTag.Name = '1021.0001 - Plant';
        assetTag.Plant_Business_Segment__c = 'EV';
        assetTag.Operator__c = 'CalCom';
        assetTag.Service_Region__c = 'DG - CO';
        assetTag.RecordTypeId = rtId;
         assetTag.Plant_Name__c ='test';
        assetTag.Customer_Plant_Asset_ID__c='678.908';
        assetTag.Full_plant_name__c='test 123345';
        insert assetTag;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(parentAcct);
        ParentAccountController c = new ParentAccountController(sc);
        PageReference pageRef = Page.ParentAccountPage;
        pageRef.getParameters().put('id', String.valueOf(parentAcct.Id));
        Test.setCurrentPage(pageRef);
        
        c.account = new Account();
        c.account.Name = 'Project Account Test';
        c.account.ParentId = parentAcct.id;
        c.account.Account_Email__c = 'anyuser@gmail.com';
        c.account.Site = 'www.google.com';
        c.accountNext();
        
        c.contact.FirstName = 'Test first name';
        c.contact.LastName = 'Test last name';
        c.contact.Email = 'contactemail@gmail.com';
        c.contact.Phone = '5546747737';
        c.contactNext();
        
        c.contactPrevious();
        //c.assetTagPrevious();
        c.cancel();
        //c.populateCustomerId();
        c.save();
    }
    }