force-app/main/default/objects/Plant_Asset__c/Plant_Asset__c.object-meta.xml
<CustomObject>
    <description>All the assets of customers</description>
    <label>Plant Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Assets (Account)</relationshipLabel>
    <relationshipName>Plant_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Assigned_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact for Onboarding</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plant Assets</relationshipLabel>
    <relationshipName>Plant_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Implementation_Status__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Status__c</fullName>
    <label>Implementation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Lifecycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Submission</fullName>
                <default>true</default>
                <label>Pending Customer Submission</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Pending Full Documentation Submission</fullName>
                <isActive>false</isActive>
                <label>Pending Full Documentation Submission</label>
            </value>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
                <isActive>false</isActive>
                <label>Submitted – Pending Customer Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plant_Asset__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Parent Asset</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>Plant Assets (Child)</relationshipLabel>
    <relationshipName>Plant_Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <inlineHelpText>Please enter the minimum required name of the asset. This field will then be concatenated with Customer plant asset ID to arrive at the asset name.</inlineHelpText>
    <label>Plant Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Asset__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Data Connection</fullName>
            </value>
            <value>
                <fullName>Data Validation</fullName>
            </value>
            <value>
                <fullName>Customer Validation</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI__c/RFI__c.object-meta.xml
<CustomObject>
    <label>RFI</label>
    <nameField>
        <label>RFI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/Assigned_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact for Onboarding</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot create an RFI while plant asset is in this Project Lifecycle Status. Change status to appropriate PLS to create RFI</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Assigned_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact for Onboarding</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Description__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Description__c</fullName>
    <label>Onsite Remediation Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Required__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Required__c</fullName>
    <label>Onsite Remediation Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot edit RFI until Plant Asset&apos;s Project Lifecycle Status is changed</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Detail_Owner__c.field-meta.xml
<CustomField>
    <fullName>RFI_Detail_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RFI Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Item_Status__c</fullName>
    <label>RFI Item Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
            </value>
            <value>
                <fullName>Completed – Pending PF Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Completed - Pending PF Review</fullName>
                <isActive>false</isActive>
                <label>Completed - Pending PF Review</label>
            </value>
            <value>
                <fullName>Submitted - pending customer review</fullName>
                <isActive>false</isActive>
                <label>Submitted - pending customer review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Number__c.field-meta.xml
<CustomField>
    <fullName>RFI_Number__c</fullName>
    <label>RFI Number</label>
    <referenceTo>RFI__c</referenceTo>
    <relationshipName>RFI_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DailyReportCustomerScheduleTest.cls
@isTest(SeeAllData='true')
public class DailyReportCustomerScheduleTest {
     @isTest
    static void testRFIReportSchedule()
    {
        
         Account newAcc = new Account();
        newAcc.Name = 'Test ACC';
        insert newAcc;
         Contact c = new Contact();
        c.LastName = 'Test Name';
        c.AccountId = newAcc.Id;
        c.Email='Kranthi.d@congruentindai.com';
        insert c;
      
        system.debug('contact--->'+ c);
        
        newAcc.Primary_Contact__c = c.Id;
        update newAcc;
     User u = new User(
     ProfileId = [SELECT Id FROM Profile WHERE Name = 'PF Community'].Id,
     LastName = 'last',
     Email = 'puser000@cittest.com',
     Username = 'puser000@cittest.com' + System.currentTimeMillis(),
     CompanyName = 'TEST',
     Title = 'title',
     Alias = 'alias',
     TimeZoneSidKey = 'America/Los_Angeles',
     EmailEncodingKey = 'UTF-8',
     LanguageLocaleKey = 'en_US',
     LocaleSidKey = 'en_US',
     ContactId = c.Id
    );
      
      insert u;        
        Plant_Asset__c palntAsset = new Plant_Asset__c();
        palntAsset.Name = 'Plant Asset st';
        palntAsset.RecordTypeId = [SELECT id from RecordType where Name ='Parent Asset'].Id;
        palntAsset.Project_Lifecycle_Status__c = 'Pending';
        palntAsset.Plant_Name__c = 'test';
        palntAsset.Implementation_Status__c = 'Pending Customer Submission';
        insert palntAsset;
        
        Plant_Asset__c palntAss = new Plant_Asset__c();
        palntAss.Name = 'Customer Asset Test';
        palntAss.RecordTypeId = [SELECT id from RecordType where Name ='Customer Asset'].Id;
        palntAss.Parent__c = palntAsset.Id;
        palntAss.Plant_Name__c = 'test123';
        palntAss.Customer_Plant_Asset_ID__c = '123';
        palntAss.Account__c = newAcc.Id;
        palntAss.Assigned_Customer_Contact__c = c.Id;
        insert palntAss;
         palntAss.Project_Lifecycle_Status__c = 'Data Validation';
        palntAss.Implementation_Status__c = 'In Progress';
        Update palntAss;
       
        RFI__c newrfi = new RFI__c();
        newrfi.Plant_Asset__c = palntAss.Id;
        insert newrfi;
        system.debug('RFI:-' +newrfi);
        
        RFI_Detail__c rfDetail = new RFI_Detail__c();
        rfDetail.RFI_Number__c = newrfi.id;
        rfDetail.Onsite_Remediation_Required__c = 'Yes';
        rfDetail.Onsite_Remediation_Description__c ='Test';
        rfDetail.Due_Date__c = Date.today().addDays(-8);
		rfDetail.RFI_Detail_Owner__c = u.Id;
        rfDetail.RFI_Item_Status__c = 'Submitted – Pending Customer Review';
         insert rfDetail;
          system.debug('rfDetail##'+rfDetail);  
         /*RFI_Detail__c rfDetail1 = new RFI_Detail__c();
        rfDetail1.RFI_Number__c = newrfi.id;
        rfDetail1.Onsite_Remediation_Required__c = 'Yes';
        rfDetail1.Onsite_Remediation_Description__c ='Test';
        rfDetail1.RFI_Item_Status__c = 'Submitted – Pending Customer Review';
          rfDetail1.Due_Date__c = Date.today().addDays(-1);
         insert rfDetail1;
        rfDetail1.RFI_Item_Status__c = 'In Progress';
        Update rfDetail1;
          RFI_Detail__c rfDetail2 = new RFI_Detail__c();
        rfDetail2.RFI_Number__c = newrfi.id;
        rfDetail2.Onsite_Remediation_Required__c = 'Yes';
        rfDetail2.Onsite_Remediation_Description__c ='Test';
        rfDetail2.RFI_Item_Status__c = 'Needs Detail';
        rfDetail.RFI_Detail_Owner__c = u.Id;
          rfDetail2.Due_Date__c = Date.today().addDays(-8);
         insert rfDetail2;*/
        
        
      Test.StartTest();
        
        String CRON_EXP = '0 0 23 * * ?'; 
       DailyReportCustomerSchedule reportSchedule = new DailyReportCustomerSchedule();
      // reportSchedule.sendmail();
        String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new DailyReportCustomerSchedule());
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }

}