force-app/main/default/objects/Plant_Asset__c/Plant_Asset__c.object-meta.xml
<CustomObject>
    <description>All the assets of customers</description>
    <label>Plant Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI__c/RFI__c.object-meta.xml
<CustomObject>
    <label>RFI</label>
    <nameField>
        <label>RFI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot create an RFI while plant asset is in this Project Lifecycle Status. Change status to appropriate PLS to create RFI</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFIs</relationshipLabel>
    <relationshipName>RFIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RFI__c/fields/RFI_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Status__c</fullName>
    <label>RFI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
                <isActive>false</isActive>
                <label>Cannot Complete</label>
            </value>
            <value>
                <fullName>Completed – Pending PF Review</fullName>
                <isActive>false</isActive>
                <label>Completed – Pending PF Review</label>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
                <isActive>false</isActive>
                <label>Needs Detail</label>
            </value>
            <value>
                <fullName>New – Pending Customer Review (New)</fullName>
                <isActive>false</isActive>
                <label>New – Pending Customer Review (New)</label>
            </value>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
                <isActive>false</isActive>
                <label>Submitted – Pending Customer Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Categories__c/RFI_Categories__c.object-meta.xml
<CustomObject>
    <label>RFI Category</label>
    <nameField>
        <label>RFI Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI_Categories__c/fields/Category_Classification__c.field-meta.xml
<CustomField>
    <fullName>Category_Classification__c</fullName>
    <description>Category Classification (General,Solar,Wind,Other )</description>
    <label>Category Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFI_Detail__c/fields/Category_Classification__c.field-meta.xml
<CustomField>
    <fullName>Category_Classification__c</fullName>
    <label>Category Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Incorrect_Category__c.field-meta.xml
<CustomField>
    <fullName>Incorrect_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incorrect Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipName>RFI_Incorrect_Information_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Missing_Incomplete_Category__c.field-meta.xml
<CustomField>
    <fullName>Missing_Incomplete_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Missing/Incomplete Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipName>RFI_Missing_Incorrect_Information_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Required__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Required__c</fullName>
    <label>Onsite Remediation Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/Plant_Asset__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot edit RFI until Plant Asset&apos;s Project Lifecycle Status is changed</errorMessage>
        <filterItems>
            <field>Plant_Asset__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Asset</value>
        </filterItems>
        <filterItems>
            <field>Plant_Asset__c.Project_Lifecycle_Status__c</field>
            <operation>notEqual</operation>
            <value>Pending, Customer Validation, Operations, Decommissioned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plant_Asset__c</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Detail_Description__c.field-meta.xml
<CustomField>
    <fullName>RFI_Detail_Description__c</fullName>
    <label>RFI Item Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Item_Status__c</fullName>
    <label>RFI Item Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted – Pending Customer Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
            </value>
            <value>
                <fullName>Completed – Pending PF Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
            <value>
                <fullName>Completed - Pending PF Review</fullName>
                <isActive>false</isActive>
                <label>Completed - Pending PF Review</label>
            </value>
            <value>
                <fullName>Submitted - pending customer review</fullName>
                <isActive>false</isActive>
                <label>Submitted - pending customer review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFI_Detail__c/fields/RFI_Number__c.field-meta.xml
<CustomField>
    <fullName>RFI_Number__c</fullName>
    <label>RFI Number</label>
    <referenceTo>RFI__c</referenceTo>
    <relationshipName>RFI_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddRfiDetail.cls
public class AddRfiDetail {
    //for rfi category
    @AuraEnabled
    public static List<wrapperClassNew> getMissingCat(sObject objectNeeded,String fieldNeeded,String recordTypeName){
        List<RFI_Categories__c> listMissingCat = [select Id, Name,RecordType.Name,Description__c,Category_Classification__c from RFI_Categories__c where RecordType.Name =:recordTypeName ORDER BY Category_Classification__c ASC];
        List<wrapperClassNew> returnwrapperClass = new  List<wrapperClassNew> ();     
        
        //to get picklist
        List<String> pickList = new List<String>();
        Schema.sObjectType objType = objectNeeded.getSObjectType();
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        MAP<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        List < Schema.PicklistEntry> values = fieldMap.get(fieldNeeded).getDescribe().getPickListValues();
        for (Schema.PicklistEntry a: values) {
            pickList.add(a.getValue());
        }
        pickList.sort();
        
        // Assign Values
        if(listMissingCat.size() > 0){
            for(RFI_Categories__c cat : listMissingCat){
                wrapperClassNew ins = new wrapperClassNew();
                ins.lstRfiCat = cat;
                ins.description = '';
               // ins.statusPicklist = pickList;
                ins.selOption = '';
                returnwrapperClass.add(ins);
            }
        }
        return returnwrapperClass;    
    }
    
    //for two category
    @AuraEnabled
    public static String processCatValues(Map<String,String> selectedCategory, String recordId){
        String value; 
        List<RFI_Detail__c> lstMissingDetail = new List<RFI_Detail__c>();
        
        for(String str: selectedCategory.keySet()){
            for(RFI_Categories__c rfi : [SELECT Id,RecordType.Name FROM RFI_Categories__c WHERE Id=:str]){
                wrapperClassNew wrpCls	= (wrapperClassNew)JSON.deserialize(selectedCategory.get(str), wrapperClassNew.class);
                RFI_Detail__c rfiDetial = new RFI_Detail__c();
                if(rfi.RecordType.Name == 'Incorrect Information'){
                    rfiDetial.Incorrect_Category__c = rfi.Id;
                }else if(rfi.RecordType.Name == 'Missing/Incomplete Information'){
                    rfiDetial.Missing_Incomplete_Category__c = rfi.Id;
                }
                rfiDetial.RFI_Number__c = recordId;//record Id
                rfiDetial.RFI_Detail_Description__c = wrpCls.description;
                rfiDetial.RFI_Item_Status__c 		= wrpCls.selOption;
                lstMissingDetail.add(rfiDetial);
            } 
        }
        
        try{
            RFIBatchProcess be = new RFIBatchProcess(lstMissingDetail);
            value = Database.executeBatch(be,25);
        }catch(Exception e){
            System.debug('Error in insert');
        }
        return value;           
    }
    
    //add RFI with RFI detail 
    @AuraEnabled
    public static String processRfiWithRfiDetail(Map<String,String> selectedCategory,
                                                 String recordId,List<String> selectedPlant){
                                                     
                                                     // return selectedMissingCat.size()+'-'+selectedIncorrectCat.size();
                                                     List<RFI_Detail__c> lstMissingDetail = new List<RFI_Detail__c>();
                                                     List<RFI__c> lstRFI = new List<RFI__c>();
                                                     String value; 
                                                     
                                                     for(String plantVar : selectedPlant){
                                                         RFI__c rfiVar = new RFI__c();
                                                         rfiVar.Plant_Asset__c = plantVar;
                                                        // rfiVar.Onsite_Remediation_Required__c = 'No';
                                                         lstRFI.add(rfiVar);                                         
                                                     }                                                                       
                                                     try{                                                  
                                                         insert lstRFI;
                                                     }catch(Exception e){
                                                         System.debug('Error in insert');
                                                     }
                                                     //    return value;     
                                                     if(lstRFI.size()>0){  
                                                         for(RFI__c idVar : lstRFI){                                                            
                                                             for(RFI_Categories__c rfi : [SELECT Id,RecordType.Name FROM RFI_Categories__c WHERE Id=:selectedCategory.keySet()]){
                                                                 wrapperClassNew wrpCls	= (wrapperClassNew)JSON.deserialize(selectedCategory.get(rfi.Id), wrapperClassNew.class);
                                                                 RFI_Detail__c rfiDetial = new RFI_Detail__c();
                                                                 if(rfi.RecordType.Name == 'Incorrect Information'){
                                                                     rfiDetial.Incorrect_Category__c = rfi.Id;
                                                                 }else if(rfi.RecordType.Name == 'Missing/Incomplete Information'){
                                                                     rfiDetial.Missing_Incomplete_Category__c = rfi.Id;
                                                                 }
                                                                 rfiDetial.RFI_Number__c = idVar.Id;//record Id
                                                                 rfiDetial.RFI_Detail_Description__c = wrpCls.description;
                                                                 rfiDetial.RFI_Item_Status__c 		= wrpCls.selOption;
                                                                 lstMissingDetail.add(rfiDetial);
                                                             } 
                                                         }
                                                     }
                                                     try{
                                                         RFIBatchProcess be = new RFIBatchProcess(lstMissingDetail);
                                                         value = Database.executeBatch(be,25);
                                                     }catch(Exception e){
                                                         System.debug('Error in insert');
                                                     }
                                                     return value;
                                                 }
    
    @AuraEnabled
    public static List<RFI_Detail__c> RfiDetails(Map<String,String> selectedCategory){
        System.debug('selectedCategory:--->' +selectedCategory);
        Set<Id> catId = new Set<Id>();
        for(String s:selectedCategory.keySet()){
            catId.add(s);
        }
        
        System.debug('selectedCat' +catId.size());
        List<RFI_Detail__c> rfiDetailLst =  [select Id,RFI_Number__r.name,Name,Customer_Comments__c,RFI_Detail_Description__c from RFI_Detail__c where Incorrect_Category__c =:catId and RFI_Number__r.RFI_Status__c!='Closed' ];
        List<RFI_Detail__c> rfiDetailLst1 =  [select Id,RFI_Number__r.name,Name,Customer_Comments__c,RFI_Detail_Description__c from RFI_Detail__c where Missing_Incomplete_Category__c =:catId and RFI_Number__r.RFI_Status__c!='Closed'];  
        rfiDetailLst.addAll(rfiDetailLst1);
        System.debug('rfiDetailLst' +rfiDetailLst1.size());
        System.debug('rfiDetailLst:-' +rfiDetailLst.size());
        //List<Contact> conLst = [select id,name from contact];
        return rfiDetailLst;
    }
    
    
    @AuraEnabled
    public static List<RFI_Detail__c> saveRfiDetailsLst(Map<String,String> selectedCat){
        System.debug('selectedCat' +selectedCat);
        List<RFI_Detail__c> rfiDetailLst = new List<RFI_Detail__c>();
        for(String s:selectedCat.keySet() ){
            RFI_Detail__c rfdetail = new RFI_Detail__c();
          Map<String, Object> m =   (Map<String, Object>) JSON.deserializeUntyped(selectedCat.get(s));
            rfdetail.id = m.get('Id').toString();
            if(m.get('Customer_Comments__c')!= null){
            rfdetail.Customer_Comments__c = m.get('Customer_Comments__c').toString();
            }
            rfiDetailLst.add(rfdetail);
            System.debug('m id value' +m.get('Id'));
             System.debug('cc value' +m.get('Customer_Comments__c'));
            
        }
        update rfiDetailLst;
        return rfiDetailLst;
    }
}