force-app/main/default/objects/Attribute_Requirement__c/Attribute_Requirement__c.object-meta.xml
<CustomObject>
    <description>Stores the base asset&apos;s attribute requirement information to be fetched in prompt screens</description>
    <label>Attribute Requirement</label>
    <nameField>
        <displayFormat>AR-{0000000}</displayFormat>
        <label>Attribute Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attribute_Requirement__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <label>Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attribute_Requirement__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <description>To collect the whcih system the core attribute is required</description>
    <inlineHelpText>Select one value in which system this attribute is required</inlineHelpText>
    <label>System</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRIVE</fullName>
            </value>
            <value>
                <fullName>DRIVE+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Core Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Attribute__c/fields/Base_Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Name__c</fullName>
    <description>To link the attributes to the relevant Base Asset</description>
    <label>Base Asset Name</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Core Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestAvoidDuplicateEntry.cls
@isTest
public class TestAvoidDuplicateEntry {
    @isTest static void AvoidDuplicateEntryonCoreAttribute() {
        Base_Asset_Template__c BassitTemplate = new Base_Asset_Template__c(Description__c ='TestDescritpion');
        insert BassitTemplate;
        Core_Attribute__c CAttribute = new Core_Attribute__c(Name ='Test Attribute',Base_Asset_Name__c =BassitTemplate.id );
        insert CAttribute;
        Attribute_Requirement__c AttReq = new Attribute_Requirement__c(Core_Attribute__c =CAttribute.id,Required__c ='Yes',System__c= 'Drive');
        insert AttReq;
        Attribute_Requirement__c SecondAttReq = new Attribute_Requirement__c(Core_Attribute__c =CAttribute.id,Required__c ='Yes',System__c= 'Drive');
        Test.startTest();
        insert SecondAttReq;
        Test.stopTest();
        
    }
}